sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -U pylint coverage pycodestyle pydocstyle

install:
  - pip install -U -e .

script:
  - pycodestyle libagent
  - pylint --reports=no --rcfile .pylintrc libagent
  - pydocstyle libagent
  - coverage run --source libagent/ -m py.test -v

after_success:
  - coverage report

